# Version of the data TOML format.
data_config_version=0

[[datasets]]
name="automap_cyclops"
description="Automap: A standard large scale images dataset"
uuid="e7fd7080-e346-4a68-9ca9-98593a99266a"

    [datasets.storage]
    driver="FileSystem"
    type="BlobTree"
    path="/home/naxos2-raid1/taylor/Data/ML_Data/FastMRI/Knee_single"

